### ISSUE TITLE
Add Deye SUN-XL02-B

### ISSUE THREAD

**Issue by mateox79** [davidrapan/ha-solarman#999]
### Is your feature request related to a problem?

It's a Deye  Sun-XL02-B optimizer concentrator.
It has a internal wifi data logger. My firmware version is MW4_32_5418_SS_04_00.00.00.04, in case that's relevant. 
The web interface is the same as my Sun 6K data logger's. 
Port 8899 is open, just like on the inverter's data logger. 
Currently, I can only view the data on DeyeCloud.

### Describe the solution you'd like

I dont know :)

### Describe alternatives you've considered

I can see  panel production with each optimizer
Watts, voltage, Amps,..

**Comment by davidrapan** [comment]
Hi @mateox79, have you tried any of the existing Deye profiles (`deye_micro`)?

**Comment by mateox79** [comment]
Yes. I have tried micro. 
Error setupening. 'NoneType' object has no attribute 'parser'

**Comment by davidrapan** [comment]
[Enabling debug logging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging)

**Comment by mateox79** [comment]
> [Enabling debug logging](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging)

[latest-2.txt](https://github.com/user-attachments/files/26011013/latest-2.txt)
iP  192.168.7.210

My inverter (works ok with solarman si 192.168.7.200).for filter the log

**Comment by tumbochka** [comment]
Any updates with this issue?
