### ISSUE TITLE
Integration not working in HA 2026.2.0

### ISSUE THREAD

**Issue by mjimeneznet** [davidrapan/ha-solarman#964]
### Description

After upgrading to HA Version: 2026.2.0 the integration doesn't load anymore.

Error:  Error setuping Inverter: 'NoneType' object has no attribute 'parser'

### Reproduction Steps

Trying to start the integration.

### Log

Error setuping Inverter: 'NoneType' object has no attribute 'parser'

### Version

25.08.16

### Home Assistant Core Version

2026.2.0

### Home Assistant Operating System Version

17.0

**Comment by sumitk31** [comment]
what is your logger model?
https://github.com/davidrapan/ha-solarman/issues/952

Latest logger from Deye only exposing data to cloud.

**Comment by mjimeneznet** [comment]
It was already working today until I upgraded Home Assistant.

![Image](https://github.com/user-attachments/assets/310d80c1-94e7-4da4-952f-8413d4bdb55c)

**Comment by mjimeneznet** [comment]
I just noticed that it works again. WEIRD because I didn't touch anything to recover it. The following screenshot shows the missing metrics while it was failing.

I'm closing the issue since it's working.

<img width="508" height="310" alt="Image" src="https://github.com/user-attachments/assets/75333bd9-6226-4bd4-906d-1c658dee1107" />

**Comment by davidrapan** [comment]
This could be caused by a variety of issues... most likely the network though.
