### ISSUE TITLE
Sofar: Can't connect to LSW-3

### ISSUE THREAD

**Issue by lukee12zakk** [davidrapan/ha-solarman#519]
### Description

I can't connect my loger with my solar setup. Just gives me errors.
Serial number begins with: 2393xxxxxx
firmware on the logger: LSW3_15_MQTT_270A_1.10
firmware on the inverter: unknown. Does not show
Also, the serial number, and model number are not shown.

### Reproduction Steps

1. install this using hacs
2. reboot home assistant and setup integration
3. connect loger stick and then gives error

### Log

2025-04-05 16:18:06.680 WARNING (SyncWorker_0) [annotatedyaml.constructors] YAML file /config/configuration.yaml contains duplicate key "themes". Check lines 5 and 6
2025-04-05 16:18:06.689 WARNING (SyncWorker_0) [annotatedyaml.constructors] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 13 and 52
2025-04-05 16:18:06.751 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hass_agent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.753 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spook which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.755 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration fontawesome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.756 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ui_lovelace_minimalist which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.757 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.759 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration truenas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.760 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration powercalc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.761 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration llama_conversation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.763 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dwains_dashboard which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.765 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ssh which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.766 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solarman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.768 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spook_inverse which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.769 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.770 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ollama_conversation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.772 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.774 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.775 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:06.776 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration network_scanner which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-05 16:18:11.024 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2385, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 644, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2904, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2388, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 761, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 646, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W' but no default was specified
2025-04-05 16:18:11.039 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W) renders=4>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2385, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 644, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2904, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2388, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 761, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 646, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W' but no default was specified
2025-04-05 16:18:12.151 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'browser_mod' accessed lovelace_data['resources'] instead of lovelace_data.resources at custom_components/browser_mod/mod_view.py, line 59: resources = hass.data["lovelace"]["resources"]. This will stop working in Home Assistant 2026.2, please report it to the author of the 'browser_mod' custom integration
2025-04-05 16:18:12.398 WARNING (SyncWorker_4) [annotatedyaml.constructors] YAML file /config/configuration.yaml contains duplicate key "themes". Check lines 5 and 6
2025-04-05 16:18:12.404 WARNING (SyncWorker_4) [annotatedyaml.constructors] YAML file /config/configuration.yaml contains duplicate key "sensor". Check lines 13 and 52
2025-04-05 16:18:13.566 ERROR (MainThread) [custom_components.ui_lovelace_minimalist.base] HACS Frontend repo "lovelace-state-switch" is not installed, See Integration Configuration.
2025-04-05 16:18:17.249 WARNING (MainThread) [homeassistant.components.heos.coordinator] The HEOS System is not logged in: Enter credentials in the integration options to access favorites and streaming services
2025-04-05 16:18:19.567 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID new_home_assistant_version already exists - ignoring automation.new_home_assistant_version
2025-04-05 16:18:19.567 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID new_home_assistant_version already exists - ignoring automation.new_home_assistant_version
2025-04-05 16:18:25.673 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W) renders=14>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2385, in forgiving_float_filter
    return float(value)
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 644, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2904, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2388, in forgiving_float_filter
    raise_no_default("float", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 761, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 646, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ states("sensor.luke_s_bed_power_power") |float + states("sensor.luke_s_desk_power_power") | float   }}W' but no default was specified
2025-04-05 16:18:33.187 WARNING (MainThread) [custom_components.hacs] You have 'Kibibit/hass-kibibit-theme' installed with HACS this repository has been removed from HACS, please consider removing it. Removal reason (Not maintained anymore)
2025-04-05 16:18:33.625 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'spook' accessed lovelace_data['dashboards'] instead of lovelace_data.dashboards at custom_components/spook/ectoplasms/lovelace/repairs/unknown_entity_references.py, line 45: self._dashboards = self.hass.data["lovelace"]["dashboards"]. This will stop working in Home Assistant 2026.2, please create a bug report at https://github.com/frenck/spook/issues
2025-04-05 16:18:50.459 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{('hold' in trigger.payload_json.action) or ('release' in trigger.payload_json.action) or 'press' in trigger.payload_json.action}}'
2025-04-05 16:18:50.463 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{('hold' in trigger.payload_json.action) or ('release' in trigger.payload_json.action) or 'press' in trigger.payload_json.action}}'
2025-04-05 16:18:50.463 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{('hold' in trigger.payload_json.action) or ('release' in trigger.payload_json.action) or 'press' in trigger.payload_json.action}}'
2025-04-05 16:19:15.501 DEBUG (MainThread) [custom_components.solarman.config_flow] ConfigFlowHandler.async_step_user: None
2025-04-05 16:19:15.501 DEBUG (MainThread) [custom_components.solarman.discovery] _discover_all: Broadcasting on [IPv4Network('192.168.1.0/24'), IPv4Network('172.30.32.0/23'), IPv4Network('172.30.232.0/23')]
2025-04-05 16:19:15.502 DEBUG (MainThread) [custom_components.solarman.discovery] DiscoveryProtocol: Send to ['192.168.1.255', '172.30.33.255', '172.30.233.255']
2025-04-05 16:19:15.577 DEBUG (MainThread) [custom_components.solarman.discovery] DiscoveryProtocol: [192.168.1.80, E8FDF83A15CA, 2393929195]
2025-04-05 16:19:16.078 DEBUG (MainThread) [custom_components.solarman.discovery] DiscoveryProtocol: Connection closed
2025-04-05 16:19:16.080 DEBUG (MainThread) [custom_components.solarman.config_flow] step_user_data_schema: custom_components/solarman/inverter_definitions/: ['Auto', 'afore_2mppt.yaml', 'afore_BNTxxxKTL-2mppt.yaml', 'afore_hybrid.yaml', 'chint_cps-scetl.yaml', 'deye_hybrid.yaml', 'deye_micro.yaml', 'deye_p3.yaml', 'deye_string.yaml', 'invt_xd-tl.yaml', 'kstar_hybrid.yaml', 'megarevo_r-3h.yaml', 'pylontech_Force-H.yaml', 'renon_ifl.yaml', 'sofar_g3hyd.yaml', 'sofar_hyd-es.yaml', 'sofar_lsw3.yaml', 'sofar_tlx-g3.yaml', 'sofar_wifikit.yaml', 'solarman_dtsd422-d3.yaml', 'solis_1p-5g.yaml', 'solis_3p-4g.yaml', 'solis_3p-5g.yaml', 'solis_hybrid.yaml', 'solis_s6-gr1p.yaml', 'srne_asf.yaml', 'swatten_sih-th.yaml', 'tsun_tsol-ms.yaml', 'zcs_azzurro-1ph-tl-v3.yaml', 'zcs_azzurro-hyd-zss-hp.yaml', 'zcs_azzurro-ktl-v3.yaml']
2025-04-05 16:19:16.080 DEBUG (MainThread) [custom_components.solarman.config_flow] step_user_data_schema: data_schema: {'name': <class 'str'>, 'sn': All(Coerce(int, msg=None), Range(min=0, max=4294967295, min_included=True, max_included=True, msg=None), msg=None), 'host': <class 'str'>, 'port': All(Coerce(int, msg=None), Range(min=1, max=65535, min_included=True, max_included=True, msg=None), msg=None), 'lookup_file': In(['Auto', 'afore_2mppt.yaml', 'afore_BNTxxxKTL-2mppt.yaml', 'afore_hybrid.yaml', 'chint_cps-scetl.yaml', 'deye_hybrid.yaml', 'deye_micro.yaml', 'deye_p3.yaml', 'deye_string.yaml', 'invt_xd-tl.yaml', 'kstar_hybrid.yaml', 'megarevo_r-3h.yaml', 'pylontech_Force-H.yaml', 'renon_ifl.yaml', 'sofar_g3hyd.yaml', 'sofar_hyd-es.yaml', 'sofar_lsw3.yaml', 'sofar_tlx-g3.yaml', 'sofar_wifikit.yaml', 'solarman_dtsd422-d3.yaml', 'solis_1p-5g.yaml', 'solis_3p-4g.yaml', 'solis_3p-5g.yaml', 'solis_hybrid.yaml', 'solis_s6-gr1p.yaml', 'srne_asf.yaml', 'swatten_sih-th.yaml', 'tsun_tsol-ms.yaml', 'zcs_azzurro-1ph-tl-v3.yaml', 'zcs_azzurro-hyd-zss-hp.yaml', 'zcs_azzurro-ktl-v3.yaml']), 'additional_options': <homeassistant.data_entry_flow.section object at 0x7f45cf876a50>}
2025-04-05 16:19:17.714 DEBUG (MainThread) [custom_components.solarman.config_flow] ConfigFlowHandler.async_step_user: {'name': 'Inverter', 'sn': 2393929195, 'host': '192.168.1.80', 'port': 8899, 'lookup_file': 'Auto', 'additional_options': {'mod': False, 'mppt': 4, 'phase': 3, 'pack': -1, 'battery_nominal_voltage': 48, 'battery_life_cycle_rating': 6000, 'mb_slave_id': 1}}
2025-04-05 16:19:17.714 DEBUG (MainThread) [custom_components.solarman.config_flow] validate_connection: {'name': 'Inverter', 'sn': 2393929195, 'host': '192.168.1.80', 'port': 8899, 'lookup_file': 'Auto', 'additional_options': {'mod': False, 'mppt': 4, 'phase': 3, 'pack': -1, 'battery_nominal_voltage': 48, 'battery_life_cycle_rating': 6000, 'mb_slave_id': 1}}
2025-04-05 16:19:17.714 DEBUG (MainThread) [custom_components.solarman.config_flow] validate_connection: validation passed: {'name': 'Inverter', 'sn': 2393929195, 'host': '192.168.1.80', 'port': 8899, 'lookup_file': 'Auto', 'additional_options': {'mod': False, 'mppt': 4, 'phase': 3, 'pack': -1, 'battery_nominal_voltage': 48, 'battery_life_cycle_rating': 6000, 'mb_slave_id': 1}}
2025-04-05 16:19:17.715 DEBUG (MainThread) [custom_components.solarman] async_setup_entry({'created_at': '2025-04-05T15:19:17.714979+00:00', 'data': {'name': 'Inverter'}, 'discovery_keys': {}, 'disabled_by': None, 'domain': 'solarman', 'entry_id': '01JR38HSYJVM1QAH7CJXGHCFVH', 'minor_version': 7, 'modified_at': '2025-04-05T15:19:17.714982+00:00', 'options': {'sn': 2393929195, 'host': '192.168.1.80'}, 'pref_disable_new_entities': False, 'pref_disable_polling': False, 'source': 'user', 'subentries': [], 'title': 'Inverter', 'unique_id': None, 'version': 1})
2025-04-05 16:19:17.715 DEBUG (MainThread) [custom_components.solarman] async_setup_entry: config_entry.runtime_data.async_config_entry_first_refresh
2025-04-05 16:19:17.715 DEBUG (MainThread) [custom_components.solarman.discovery] _discover: Broadcasting on 192.168.1.80
2025-04-05 16:19:17.717 DEBUG (MainThread) [custom_components.solarman.discovery] DiscoveryProtocol: Send to 192.168.1.80
2025-04-05 16:19:17.726 DEBUG (MainThread) [custom_components.solarman.discovery] DiscoveryProtocol: [192.168.1.80, E8FDF83A15CA, 2393929195]
2025-04-05 16:19:17.727 DEBUG (MainThread) [custom_components.solarman.provider] Device autodetection is enabled
2025-04-05 16:19:17.727 DEBUG (MainThread) [custom_components.solarman.device] [2393929195] Scheduling 1 query request. ^-1
2025-04-05 16:19:17.727 DEBUG (MainThread) [custom_components.solarman.device] [2393929195] Querying 03 ❘ 0x03 ~ 0000 - 0022 ❘ 0x0000 - 0x0016 #023 ...
2025-04-05 16:19:17.727 DEBUG (MainThread) [custom_components.solarman.discovery] DiscoveryProtocol: Connection closed
2025-04-05 16:19:17.737 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] Successful connection!
2025-04-05 16:19:17.738 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] SENT: a5 17 00 10 45 5c 00 eb 75 b0 8e 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 4c 15
2025-04-05 16:19:17.807 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] RECD: a5 13 00 10 15 5c 55 eb 75 b0 8e 02 01 1e 55 04 00 c8 60 00 00 d7 f4 ec 67 01 90 02 00 00 da 15
2025-04-05 16:19:17.808 DEBUG (MainThread) [pymodbus.logging] Processing: 0x1 0x90 0x2 0x0 0x0
2025-04-05 16:19:17.808 DEBUG (MainThread) [pymodbus.logging] Frame check failed, possible garbage after frame, testing..
2025-04-05 16:19:17.808 DEBUG (MainThread) [pymodbus.logging] Frame - not ready
2025-04-05 16:19:17.808 DEBUG (MainThread) [custom_components.solarman.device] [2393929195] Querying 03 ❘ 0x03 ~ 0000 - 0022 ❘ 0x0000 - 0x0016 #023 failed, attempts left: 4 [FrameError: Invalid modbus response received]
2025-04-05 16:19:17.808 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] SENT: a5 17 00 10 45 5d 00 eb 75 b0 8e 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 4d 15
2025-04-05 16:19:17.888 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] RECD: a5 13 00 10 15 5d 56 eb 75 b0 8e 02 01 1e 55 04 00 c8 60 00 00 d7 f4 ec 67 01 90 02 00 00 dc 15
2025-04-05 16:19:17.888 DEBUG (MainThread) [pymodbus.logging] Processing: 0x1 0x90 0x2 0x0 0x0
2025-04-05 16:19:17.888 DEBUG (MainThread) [pymodbus.logging] Frame check failed, possible garbage after frame, testing..
2025-04-05 16:19:17.888 DEBUG (MainThread) [pymodbus.logging] Frame - not ready
2025-04-05 16:19:17.888 DEBUG (MainThread) [custom_components.solarman.device] [2393929195] Querying 03 ❘ 0x03 ~ 0000 - 0022 ❘ 0x0000 - 0x0016 #023 failed, attempts left: 3 [FrameError: Invalid modbus response received]
2025-04-05 16:19:17.889 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] SENT: a5 17 00 10 45 5e 00 eb 75 b0 8e 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 4e 15
2025-04-05 16:19:17.969 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] RECD: a5 13 00 10 15 5e 57 eb 75 b0 8e 02 01 1e 55 04 00 c8 60 00 00 d7 f4 ec 67 01 90 02 00 00 de 15
2025-04-05 16:19:17.969 DEBUG (MainThread) [pymodbus.logging] Processing: 0x1 0x90 0x2 0x0 0x0
2025-04-05 16:19:17.969 DEBUG (MainThread) [pymodbus.logging] Frame check failed, possible garbage after frame, testing..
2025-04-05 16:19:17.969 DEBUG (MainThread) [pymodbus.logging] Frame - not ready
2025-04-05 16:19:17.969 DEBUG (MainThread) [custom_components.solarman.device] [2393929195] Querying 03 ❘ 0x03 ~ 0000 - 0022 ❘ 0x0000 - 0x0016 #023 failed, attempts left: 2 [FrameError: Invalid modbus response received]
2025-04-05 16:19:17.969 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] SENT: a5 17 00 10 45 5f 00 eb 75 b0 8e 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 4f 15
2025-04-05 16:19:18.052 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] RECD: a5 13 00 10 15 5f 58 eb 75 b0 8e 02 01 1e 55 04 00 c9 60 00 00 d7 f4 ec 67 01 90 02 00 00 e1 15
2025-04-05 16:19:18.052 DEBUG (MainThread) [pymodbus.logging] Processing: 0x1 0x90 0x2 0x0 0x0
2025-04-05 16:19:18.053 DEBUG (MainThread) [pymodbus.logging] Frame check failed, possible garbage after frame, testing..
2025-04-05 16:19:18.053 DEBUG (MainThread) [pymodbus.logging] Frame - not ready
2025-04-05 16:19:18.053 DEBUG (MainThread) [custom_components.solarman.device] [2393929195] Querying 03 ❘ 0x03 ~ 0000 - 0022 ❘ 0x0000 - 0x0016 #023 failed, attempts left: 1 [FrameError: Invalid modbus response received]
2025-04-05 16:19:18.053 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] SENT: a5 17 00 10 45 60 00 eb 75 b0 8e 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 03 00 00 00 17 05 c4 50 15
2025-04-05 16:19:18.139 DEBUG (MainThread) [custom_components.solarman.pysolarman.pysolarman] [2393929195] RECD: a5 13 00 10 15 60 59 eb 75 b0 8e 02 01 1e 55 04 00 c9 60 00 00 d7 f4 ec 67 01 90 02 00 00 e3 15
2025-04-05 16:19:18.139 DEBUG (MainThread) [pymodbus.logging] Processing: 0x1 0x90 0x2 0x0 0x0
2025-04-05 16:19:18.139 DEBUG (MainThread) [pymodbus.logging] Frame check failed, possible garbage after frame, testing..
2025-04-05 16:19:18.139 DEBUG (MainThread) [pymodbus.logging] Frame - not ready
2025-04-05 16:19:18.139 DEBUG (MainThread) [custom_components.solarman.device] [2393929195] Querying 03 ❘ 0x03 ~ 0000 - 0022 ❘ 0x0000 - 0x0016 #023 failed, attempts left: 0, aborting. [FrameError: Invalid modbus response received]
2025-04-05 16:19:18.139 INFO (MainThread) [custom_components.solarman.device] [2393929195] Closing connection to 192.168.1.80
2025-04-05 16:19:18.140 DEBUG (MainThread) [custom_components.solarman.coordinator] async_shutdown
2025-04-05 16:19:18.140 INFO (MainThread) [custom_components.solarman.device] [2393929195] Closing connection to 192.168.1.80


### Version

25.03.18

### Home Assistant Core Version

2025.4.1

### Home Assistant Operating System Version

15.1

**Comment by davidrapan** [comment]
Hi, what brand and model this is?

**Comment by lukee12zakk** [comment]
The inverter is a sofar solar hybrid inverter with a model number of HYD 3000-EP.

**Comment by davidrapan** [comment]
You need to select appropriate profile (e.g. [zcs_azzurro-hyd-zss-hp.yaml](https://github.com/davidrapan/ha-solarman/blob/main/custom_components/solarman/inverter_definitions/zcs_azzurro-hyd-zss-hp.yaml)). Autodetection is only for Deye compatible devices.

**Comment by lukee12zakk** [comment]
Thanks. That fixed it. I've never done this before and this was all very confusing for me, so thank you for helping me.

**Comment by lukee12zakk** [comment]
hey, that profile is missing, and im getting errors on the latest version, and on the version closest to the time i originaly made this issue, that it's not connecting and something is worng. I have error code from the last version that was made before this issue:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/__init__.py", line 38, in async_setup_entry
    config_entry.runtime_data = Coordinator(hass, Device(config))
                                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solarman/coordinator.py", line 22, in __init__
    super().__init__(hass, _LOGGER, name = device.config.name, update_interval = TIMINGS_UPDATE_INTERVAL, always_update = False)
                                           ^^^^^^^^^^^^^^^^^^
  File "src/propcache/_helpers_c.pyx", line 82, in propcache._helpers_c.cached_property.__get__
  File "/config/custom_components/solarman/provider.py", line 42, in name
    return protected(self._data.get(CONF_NAME), "Configuration parameter [name] does not have a value")
  File "/config/custom_components/solarman/common.py", line 24, in protected
    raise vol.Invalid(error)
voluptuous.error.Invalid: Configuration parameter [name] does not have a value

**Comment by davidrapan** [comment]
Look [here](https://github.com/davidrapan/ha-solarman/wiki/Supported-Devices) which file you need to use.

**Comment by lukee12zakk** [comment]
Found fix. Turns out that the fact that the profile was missing was the issue. I got the profile that you had told me to get originaly.

**Comment by davidrapan** [comment]
You should use [sofar_g3](https://github.com/davidrapan/ha-solarman/blob/main/custom_components/solarman/inverter_definitions/sofar_g3.yaml) w/ Battery packs set to 1.
