### ISSUE TITLE
Communication breakdown.

### ISSUE THREAD

**Issue by pkopczak** [davidrapan/ha-solarman#741]
### Description

After updating, there's no connection to my DEYE. The connection is made directly through the inverter, bypassing the DEYE data logger. Since version 10, this has stopped working. Communication is via TCP Modbus, Waveshare RS232/485 TO WIFI ETH (B)

### Reproduction Steps

Update

### Log

Rejestrator: homeassistant.helpers.entity_platform
Źródło: helpers/deprecation.py:222
Pierwsze zdarzenie: 10:41:06 (5829 wystąpień)
Ostatnio zalogowany: 10:44:04

The deprecated function platform_translations was called from solarman. It will be removed in HA Core 2026.8. Use platform_data.platform_translations instead, please create a bug report at https://github.com/davidrapan/ha-solarman/issues

### Version

25.08.12

### Home Assistant Core Version

2025.8.1

### Home Assistant Operating System Version

16

**Comment by pkopczak** [comment]
Version 25.06.07 and previous ones work correctly.

**Comment by davidrapan** [comment]
Hi @pkopczak, the log provided has nothing to do with your issue. Please enable debug logging and attach the file here.

**Comment by MondMann2019** [comment]
Same Problem here...

don't know, if I did it right, but here is the debug log:

[home-assistant_solarman_2025-08-13T09-14-56.749Z.log](https://github.com/user-attachments/files/21750785/home-assistant_solarman_2025-08-13T09-14-56.749Z.log)

**Comment by pkopczak** [comment]
[home-assistant_solarman_2025-08-13T09-18-10.897Z.log](https://github.com/user-attachments/files/21750798/home-assistant_solarman_2025-08-13T09-18-10.897Z.log)

**Comment by PepeOnAChair** [comment]
Exactly same problem here. "Deye SUN-12K-SG04LP3-EU" and "TCP Modbus, Waveshare RS232/485 TO WIFI ETH (B)". I also confirm that version 25.06.07 works correctly. I lost 12 hours on this bug :/

**Comment by MondMann2019** [comment]
went back to version 25.08.10 and now everything ist fine again

**Comment by pkopczak** [comment]
It doesn't work for me, I have to go back to 25.06.07. I have two recorders, the original one from Deye works after the update.

**Comment by davidrapan** [comment]
> went back to version 25.08.10 and now everything ist fine again

Your problem was a little different as v25.08.12 requires HA Core 2025.8.0+ and I was hoping that HACS would handle it, but apparently not.

> I lost 12 hours on this bug :/

How could this happen? Didn't you check if it works correctly after the update?

> [home-assistant_solarman_2025-08-13T09-18-10.897Z.log](https://github.com/user-attachments/files/21750798/home-assistant_solarman_2025-08-13T09-18-10.897Z.log)

@pkopczak, could you please elaborate some more about your setup? So I can make more sense of it (including ips, etc.), thanks.

**Comment by MondMann2019** [comment]
> > went back to version 25.08.10 and now everything ist fine again
> 
> Your problem was a little different as v25.08.12 requires HA Core 2025.8.0+ and I was hoping that HACS would handle it, but apparently not.
> 
> > I lost 12 hours on this bug :/
> 
> How could this happen? Didn't you check if it works correctly after the update?
> 
> > [home-assistant_solarman_2025-08-13T09-18-10.897Z.log](https://github.com/user-attachments/files/21750798/home-assistant_solarman_2025-08-13T09-18-10.897Z.log)
> 
> [@pkopczak](https://github.com/pkopczak), could you please elaborate some more about your setup? So I can make more sense of it (including ips, etc.), thanks.

OK, thanks! I'll wait with the update until 2025.8.3...

**Comment by pkopczak** [comment]
Of course. 
Inverter with original recorder.

![Image](https://github.com/user-attachments/assets/a6b66217-8792-4be2-a9b5-286f924f021d)

Inverter DEYE 

![Image](https://github.com/user-attachments/assets/5a87bd2b-e190-4e33-adaf-267b5044da21)
Both loggers are connected to the same Inverter. Now I have a restored working version.

<img width="974" height="493" alt="Image" src="https://github.com/user-attachments/assets/b5644b76-ceff-448e-8729-b778a5d60f57" />

**Comment by davidrapan** [comment]
Thanks.

Enable debug logging in this working version as well, click reload integration, then wait 5 minutes before closing the debug window, and attach this file here as well.

_It would be great if you could do the same later when you have some time to spare with the non-working version again too._ 😉

**Comment by pkopczak** [comment]
This is a working one.
[home-assistant_solarman_2025-08-13T10-17-05.346Z.zip](https://github.com/user-attachments/files/21752076/home-assistant_solarman_2025-08-13T10-17-05.346Z.zip)
I will prepare the second non-working one in a moment.

**Comment by pkopczak** [comment]
This is non-working. 

![Image](https://github.com/user-attachments/assets/855e4de6-20c6-4f51-8657-4528e8b2c691)

[home-assistant_solarman_2025-08-13T10-29-46.085Z.log](https://github.com/user-attachments/files/21752317/home-assistant_solarman_2025-08-13T10-29-46.085Z.log)

**Comment by davidrapan** [comment]
Mhh, it looks like it's caused by [fix: Ignoring errors/exceptions during initialization](https://github.com/davidrapan/ha-solarman/commit/441c8e219a3448c8425931e4ee3eedd9003be72c)

**Comment by davidrapan** [comment]
Mhh, it looks like it's caused by [fix: Ignoring errors/exceptions during initialization](https://github.com/davidrapan/ha-solarman/commit/441c8e219a3448c8425931e4ee3eedd9003be72c)

Any idea why is Waveshare not responding to requests for holding register number 10002? Older version just ignores it and that's why it works.

**Comment by fl1ck3r** [comment]
I also have similar issue, after update no entity is working. See log:


2025-08-13 14:24:11.973 DEBUG (MainThread) [custom_components.solarman.parser] generator_energy_sensor validation failed, triggered by state: 0.0 with conditions: {'min': 0.1}
2025-08-13 14:24:11.975 DEBUG (MainThread) [custom_components.solarman.device] [192.168.1.239] Returning 58 new values
2025-08-13 14:24:11.975 DEBUG (MainThread) [custom_components.solarman.coordinator] Finished fetching Inverter data in 0.381 seconds (success: True)
2025-08-13 14:24:11.976 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solarman/entity.py", line 44, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1019, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1141, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in __async_calculate_state
    name := (entry and entry.name) or self._friendly_name_internal()
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solarman/entity.py", line 104, in _friendly_name_internal
    if self.platform_data and (name_translation_key := self._name_translation_key) and (n := self.platform_data.platform_translations.get(name_translation_key)):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'SolarmanIntervalSensor' object has no attribute 'platform_data'. Did you mean: '_platform_state'?
^C
odroid@odroid:/opt/homeassistant$ tail -f home-assistant.log
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in __async_calculate_state
    name := (entry and entry.name) or self._friendly_name_internal()
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solarman/entity.py", line 104, in _friendly_name_internal
    if self.platform_data and (name_translation_key := self._name_translation_key) and (n := self.platform_data.platform_translations.get(name_translation_key)):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'SolarmanIntervalSensor' object has no attribute 'platform_data'. Did you mean: '_platform_state'?

**Comment by pkopczak** [comment]
Perhaps the problem is with device identification. The original recorder has the name and serial number.
- name: "Device"
        class: "enum"
        rule: 1
        registers: [0x0000]

**Comment by davidrapan** [comment]
> I also have similar issue, after update no entity is working. See log:

No you do not, [v25.08.12](https://github.com/davidrapan/ha-solarman/releases/tag/v25.08.12) is for HA Core 2025.8.0+

> Perhaps the problem is with device identification.

No, it is read just fine in both cases. 😉

**Comment by BrentVerhaegen** [comment]
Not sure if I should open a new bug report for this, but after upgrading to v2025.08.x, I also lost connection to my Deye SUN10K-SG04LP3 inverter. 
I mean, it seems like it could connect, but all the entities were `Unavailable`

I'm however not using a Waveshare adapter, I'm using using the Solarman dongle that Deye delivered with the inverter.

What I've tried/checked

- Verified that the IP is still correct
- Verified that port 8899 is still open
- Rebooted the Solarman dongle
- Restart the integration and HA

Rolling back the the v2025.06 release solved the issue immediately for me.

In the logs I found this error:


```
Logger: homeassistant
Bron: custom_components/solarman/entity.py:104
integratie: Solarman (documentatie, problemen)
Eerst voorgekomen: 10:24:25 (85 gebeurtenissen)
Laatst gelogd: 10:31:42
Error doing job: Task exception was never retrieved (None)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 180, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solarman/entity.py", line 44, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1018, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1140, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1109, in __async_calculate_state
    name := (entry and entry.name) or self._friendly_name_internal()
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solarman/entity.py", line 104, in _friendly_name_internal
    if self.platform_data and (name_translation_key := self._name_translation_key) and (n := self.platform_data.platform_translations.get(name_translation_key)):
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'SolarmanBatteryCustomSensor' object has no attribute 'platform_data'. Did you mean: '_platform_state'?
```

**Comment by davidrapan** [comment]
> Not sure if I should open a new bug report for this, but after upgrading to v2025.08.x

[v25.08.12](https://github.com/davidrapan/ha-solarman/releases/tag/v25.08.12) is for HA Core 2025.8.0+, use [v25.08.10](https://github.com/davidrapan/ha-solarman/releases/tag/v25.08.10) for previous versions of HA Core.

**Comment by BrentVerhaegen** [comment]
> > Not sure if I should open a new bug report for this, but after upgrading to v2025.08.x
> 
> [v25.08.12](https://github.com/davidrapan/ha-solarman/releases/tag/v25.08.12) is for HA Core 2025.8.0+, use [v25.08.10](https://github.com/davidrapan/ha-solarman/releases/tag/v25.08.10) for previous versions of HA Core.

v25.08.10 does indeed seem to work on my HA v2025.7.3 version. 
As a suggestion, maybe you could mention in the release notes of [v25.08.12](https://github.com/davidrapan/ha-solarman/releases/tag/v25.08.12) that this requires HA Core 2025.8.0+?
I checked the release notes before upgrading, and since there weren't any breaking changes, nor a mention of HA Core 2025.8.0+ required, I upgraded the integration and assumed it would work.

Thanks for the help.

**Comment by davidrapan** [comment]
It's in the `hacs.json` file and I thought HACS would handle it, but apparently not.

**Comment by davidrapan** [comment]
It's in the [hacs.json](https://github.com/davidrapan/ha-solarman/blob/main/hacs.json) file and I thought HACS would handle it, but apparently not.

**Comment by BrentVerhaegen** [comment]
> It's in the [hacs.json](https://github.com/davidrapan/ha-solarman/blob/main/hacs.json) file and I thought HACS would handle it, but apparently not.

Nope, the update is still suggested for me on `v2025.7.3`

<img width="574" height="593" alt="Image" src="https://github.com/user-attachments/assets/9b109d40-0e0e-4f2b-b61b-f1483a9c0418" />

**Comment by davidrapan** [comment]
> Nope

Yeah, I figured.. Anyway, here is [fix: Backward incompatibility of platform_data attribute](https://github.com/davidrapan/ha-solarman/commit/9dacf76ad2cd77b331b55a7c4eee6b4528ffd9f0)

**Comment by davidrapan** [comment]
> Nope

Yeah, I figured.. Anyway, here is [fix: Backward incompatibility of platform_data attribute](https://github.com/davidrapan/ha-solarman/commit/cd4cbc8d7c6e970fd3b883e7ef7cfec2e2d3e82a)

**Comment by fl1ck3r** [comment]
> > Nope
> 
> Yeah, I figured.. Anyway, here is [fix: Backward incompatibility of platform_data attribute](https://github.com/davidrapan/ha-solarman/commit/cd4cbc8d7c6e970fd3b883e7ef7cfec2e2d3e82a)

This worked! back online, thank you!

**Comment by davidrapan** [comment]
[fix: Ignore errors/exceptions when trying to read Number of Battery packs during initialization](https://github.com/davidrapan/ha-solarman/commit/c6c3bcd4ccf9241f4c00698115953c5dcfe58248)

**Comment by pkopczak** [comment]
This worked! Thx.

**Comment by davidrapan** [comment]
Awesome! 🎉
